services:
  - type: web
    name: safedrive-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: safedrive-db
          property: connectionString

databases:
  - name: safedrive-db
    databaseName: safedrive
    user: safedrive_user